In [1]:
# ============================================================
# 01. IMPORT LIBRARIES
# ============================================================

import pandas as pd
import numpy as np

from sqlalchemy import create_engine

print("Libraries imported successfully!")

Libraries imported successfully!

In [9]:
# ============================================================
# 02. LOAD RAW DATA
# ============================================================

file_path = r"D:\data_analyst_road_map\project\customer_churn\dataset\raw\customer_churn_dataset-training-master.csv"

df = pd.read_csv(file_path)

print("Dataset loaded successfully!")
print("Shape:", df.shape)

df.head()

Dataset loaded successfully!
Shape: (440833, 12)

,CustomerID,Age,Gender,Tenure,Usage Frequency,Support Calls,Payment Delay,Subscription Type,Contract Length,Total Spend,Last Interaction,Churn
0,2.0,30.0,Female,39.0,14.0,5.0,18.0,Standard,Annual,932.0,17.0,1.0
1,3.0,65.0,Female,49.0,1.0,10.0,8.0,Basic,Monthly,557.0,6.0,1.0
2,4.0,55.0,Female,14.0,4.0,6.0,18.0,Basic,Quarterly,185.0,3.0,1.0
3,5.0,58.0,Male,38.0,21.0,7.0,7.0,Standard,Monthly,396.0,29.0,1.0
4,6.0,23.0,Male,32.0,20.0,5.0,8.0,Basic,Monthly,617.0,20.0,1.0

In [10]:
# ============================================================
# 03. DATASET INFORMATION
# ============================================================

df.info()

<class 'pandas.DataFrame'>
RangeIndex: 440833 entries, 0 to 440832
Data columns (total 12 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   CustomerID         440832 non-null  float64
 1   Age                440832 non-null  float64
 2   Gender             440832 non-null  str
 3   Tenure             440832 non-null  float64
 4   Usage Frequency    440832 non-null  float64
 5   Support Calls      440832 non-null  float64
 6   Payment Delay      440832 non-null  float64
 7   Subscription Type  440832 non-null  str
 8   Contract Length    440832 non-null  str
 9   Total Spend        440832 non-null  float64
 10  Last Interaction   440832 non-null  float64
 11  Churn              440832 non-null  float64
dtypes: float64(9), str(3)
memory usage: 40.4 MB

In [11]:
# ============================================================
# 04. CHECK MISSING VALUES
# ============================================================

missing_values = df.isnull().sum()

print("Missing values by column:")
print(missing_values)

print("\nTotal missing values:", missing_values.sum())

Missing values by column:
CustomerID           1
Age                  1
Gender               1
Tenure               1
Usage Frequency      1
Support Calls        1
Payment Delay        1
Subscription Type    1
Contract Length      1
Total Spend          1
Last Interaction     1
Churn                1
dtype: int64

Total missing values: 12

In [12]:
# ============================================================
# 05. CHECK COMPLETELY EMPTY ROWS
# ============================================================

empty_rows = df[df.isnull().all(axis=1)]

print("Completely empty rows:", len(empty_rows))

if len(empty_rows) > 0:
    print("\nEmpty rows:")
    print(empty_rows)

Completely empty rows: 1

Empty rows:
        CustomerID  Age Gender  Tenure  Usage Frequency  Support Calls  \
199295         NaN  NaN    NaN     NaN              NaN            NaN

        Payment Delay Subscription Type Contract Length  Total Spend  \
199295            NaN               NaN             NaN          NaN

        Last Interaction  Churn
199295               NaN    NaN

In [13]:
# ============================================================
# 06. REMOVE COMPLETELY EMPTY ROWS
# ============================================================

rows_before = len(df)

df = df.dropna(how="all").copy()

rows_after = len(df)

print("Rows before:", rows_before)
print("Rows after:", rows_after)
print("Rows removed:", rows_before - rows_after)

Rows before: 440833
Rows after: 440832
Rows removed: 1

In [14]:
# ============================================================
# 07. CHECK DUPLICATE ROWS
# ============================================================

duplicate_rows = df.duplicated().sum()

print("Duplicate rows:", duplicate_rows)

Duplicate rows: 0

In [15]:
# ============================================================
# 08. CHECK DUPLICATE CUSTOMER ID
# ============================================================

duplicate_customer_id = df["CustomerID"].duplicated().sum()

print("Duplicate CustomerID:", duplicate_customer_id)

Duplicate CustomerID: 0

In [16]:
# ============================================================
# 09. CHECK CATEGORICAL VALUES
# ============================================================

categorical_columns = [
    "Gender",
    "Subscription Type",
    "Contract Length"
]

for col in categorical_columns:
    print(f"\n{col}:")
    print(df[col].unique())

Gender:
<StringArray>
['Female', 'Male']
Length: 2, dtype: str

Subscription Type:
<StringArray>
['Standard', 'Basic', 'Premium']
Length: 3, dtype: str

Contract Length:
<StringArray>
['Annual', 'Monthly', 'Quarterly']
Length: 3, dtype: str

In [17]:
# ============================================================
# 10. CLEAN CATEGORICAL VALUES
# ============================================================

for col in categorical_columns:
    df[col] = (
        df[col]
        .astype("string")
        .str.strip()
    )

print("Categorical values cleaned successfully!")

Categorical values cleaned successfully!

In [18]:
# ============================================================
# 11. CONVERT NUMERIC COLUMNS
# ============================================================

numeric_columns = [
    "Age",
    "Tenure",
    "Usage Frequency",
    "Support Calls",
    "Payment Delay",
    "Total Spend",
    "Last Interaction",
    "Churn"
]

for col in numeric_columns:
    df[col] = pd.to_numeric(
        df[col],
        errors="coerce"
    )

print("Numeric columns converted successfully!")

Numeric columns converted successfully!

In [19]:
# ============================================================
# 12. CONVERT INTEGER COLUMNS
# ============================================================

integer_columns = [
    "Age",
    "Tenure",
    "Usage Frequency",
    "Support Calls",
    "Payment Delay",
    "Last Interaction",
    "Churn"
]

for col in integer_columns:
    df[col] = df[col].astype("Int64")

print("Integer columns converted successfully!")

Integer columns converted successfully!

In [20]:
# ============================================================
# 13. FORMAT TOTAL SPEND
# ============================================================

df["Total Spend"] = df["Total Spend"].astype("float64")

df["Total Spend"] = df["Total Spend"].round(2)

print(df["Total Spend"].head())
print("\nData type:", df["Total Spend"].dtype)

0    932.0
1    557.0
2    185.0
3    396.0
4    617.0
Name: Total Spend, dtype: float64

Data type: float64

In [21]:
# ============================================================
# 14. CHECK NUMERIC RANGES
# ============================================================

print(df[numeric_columns].describe().T)

                     count        mean         std    min    25%    50%  \
Age               440832.0   39.373153   12.442369   18.0   29.0   39.0
Tenure            440832.0   31.256336   17.255727    1.0   16.0   32.0
Usage Frequency   440832.0   15.807494    8.586242    1.0    9.0   16.0
Support Calls     440832.0    3.604437    3.070218    0.0    1.0    3.0
Payment Delay     440832.0   12.965722    8.258063    0.0    6.0   12.0
Total Spend       440832.0  631.616223  240.803001  100.0  480.0  661.0
Last Interaction  440832.0   14.480868    8.596208    1.0    7.0   14.0
Churn             440832.0    0.567107    0.495477    0.0    0.0    1.0

                    75%     max
Age                48.0    65.0
Tenure             46.0    60.0
Usage Frequency    23.0    30.0
Support Calls       6.0    10.0
Payment Delay      19.0    30.0
Total Spend       830.0  1000.0
Last Interaction   22.0    30.0
Churn               1.0     1.0

In [22]:
# ============================================================
# 15. CHECK INVALID VALUES
# ============================================================

valid_ranges = {
    "Age": (18, 65),
    "Tenure": (1, 60),
    "Usage Frequency": (1, 30),
    "Support Calls": (0, 10),
    "Payment Delay": (0, 30),
    "Last Interaction": (1, 30),
    "Churn": (0, 1)
}

for col, (min_value, max_value) in valid_ranges.items():

    invalid = df[
        (df[col] < min_value) |
        (df[col] > max_value)
    ]

    print(
        f"{col}: {len(invalid)} invalid values "
        f"(expected {min_value}-{max_value})"
    )

Age: 0 invalid values (expected 18-65)
Tenure: 0 invalid values (expected 1-60)
Usage Frequency: 0 invalid values (expected 1-30)
Support Calls: 0 invalid values (expected 0-10)
Payment Delay: 0 invalid values (expected 0-30)
Last Interaction: 0 invalid values (expected 1-30)
Churn: 0 invalid values (expected 0-1)

In [23]:
# ============================================================
# 16. CHECK NEGATIVE TOTAL SPEND
# ============================================================

negative_spend = df[df["Total Spend"] < 0]

print("Negative Total Spend:", len(negative_spend))

if len(negative_spend) > 0:
    print(negative_spend)

Negative Total Spend: 0

In [24]:
# ============================================================
# 17. CHECK MISSING VALUES AFTER TYPE CONVERSION
# ============================================================

missing_after_conversion = df.isnull().sum()

print(missing_after_conversion)

print(
    "\nTotal missing values:",
    missing_after_conversion.sum()
)

CustomerID           0
Age                  0
Gender               0
Tenure               0
Usage Frequency      0
Support Calls        0
Payment Delay        0
Subscription Type    0
Contract Length      0
Total Spend          0
Last Interaction     0
Churn                0
dtype: int64

Total missing values: 0

In [25]:
# ============================================================
# 18. REMOVE REMAINING MISSING VALUES
# ============================================================

rows_before = len(df)

df = df.dropna().copy()

rows_after = len(df)

print("Rows before:", rows_before)
print("Rows after:", rows_after)
print("Rows removed:", rows_before - rows_after)

Rows before: 440832
Rows after: 440832
Rows removed: 0

In [26]:
# ============================================================
# 19. CONVERT COLUMN NAMES TO SNAKE_CASE
# ============================================================

df.columns = (
    df.columns
    .str.strip()
    .str.lower()
    .str.replace(r"[^a-z0-9]+", "_", regex=True)
    .str.strip("_")
)

print("Column names:")
print(df.columns.tolist())

Column names:
['customerid', 'age', 'gender', 'tenure', 'usage_frequency', 'support_calls', 'payment_delay', 'subscription_type', 'contract_length', 'total_spend', 'last_interaction', 'churn']

In [29]:
# ============================================================
# 20. FINAL DATA QUALITY CHECK
# ============================================================

print("=" * 60)
print("FINAL DATA QUALITY CHECK")
print("=" * 60)

print("\nShape:")
print(df.shape)

print("\nMissing values:")
print(df.isnull().sum().sum())

print("\nDuplicate rows:")
print(df.duplicated().sum())

print("\nDuplicate Customer ID:")
print(df["customerid"].duplicated().sum())

print("\nData types:")
print(df.dtypes)

============================================================
FINAL DATA QUALITY CHECK
============================================================

Shape:
(440832, 12)

Missing values:
0

Duplicate rows:
0

Duplicate Customer ID:
0

Data types:
customerid           float64
age                    Int64
gender                string
tenure                 Int64
usage_frequency        Int64
support_calls          Int64
payment_delay          Int64
subscription_type     string
contract_length       string
total_spend          float64
last_interaction       Int64
churn                  Int64
dtype: object

In [30]:
# ============================================================
# 21. CHECK CHURN DISTRIBUTION
# ============================================================

churn_counts = df["churn"].value_counts()

print("Churn counts:")
print(churn_counts)

print("\nChurn percentage:")
print(
    (df["churn"].value_counts(normalize=True) * 100)
    .round(2)
)

Churn counts:
churn
1    249999
0    190833
Name: count, dtype: Int64

Churn percentage:
churn
1    56.71
0    43.29
Name: proportion, dtype: Float64

In [31]:
# ============================================================
# 22. FINAL CATEGORICAL CHECK
# ============================================================

categorical_columns_cleaned = [
    "gender",
    "subscription_type",
    "contract_length"
]

for col in categorical_columns_cleaned:
    print(f"\n{col}:")
    print(df[col].value_counts())

gender:
gender
Male      250252
Female    190580
Name: count, dtype: Int64

subscription_type:
subscription_type
Standard    149128
Premium     148678
Basic       143026
Name: count, dtype: Int64

contract_length:
contract_length
Annual       177198
Quarterly    176530
Monthly       87104
Name: count, dtype: Int64

In [32]:
# ============================================================
# 23. FINAL NUMERIC CHECK
# ============================================================

numeric_columns_cleaned = [
    "age",
    "tenure",
    "usage_frequency",
    "support_calls",
    "payment_delay",
    "total_spend",
    "last_interaction",
    "churn"
]

print(df[numeric_columns_cleaned].describe().T)

                     count        mean         std    min    25%    50%  \
age               440832.0   39.373153   12.442369   18.0   29.0   39.0
tenure            440832.0   31.256336   17.255727    1.0   16.0   32.0
usage_frequency   440832.0   15.807494    8.586242    1.0    9.0   16.0
support_calls     440832.0    3.604437    3.070218    0.0    1.0    3.0
payment_delay     440832.0   12.965722    8.258063    0.0    6.0   12.0
total_spend       440832.0  631.616223  240.803001  100.0  480.0  661.0
last_interaction  440832.0   14.480868    8.596208    1.0    7.0   14.0
churn             440832.0    0.567107    0.495477    0.0    0.0    1.0

                    75%     max
age                48.0    65.0
tenure             46.0    60.0
usage_frequency    23.0    30.0
support_calls       6.0    10.0
payment_delay      19.0    30.0
total_spend       830.0  1000.0
last_interaction   22.0    30.0
churn               1.0     1.0

In [36]:
# ============================================================
# 24. EXPORT CLEANED DATASET
# ============================================================

output_path = r"D:\data_analyst_road_map\project\customer_churn\dataset\cleaned\customer_churn_cleaned.csv"

df.to_csv(
    output_path,
    index=False
)

print("Cleaned dataset exported successfully!")
print("File:", output_path)
print("Rows:", len(df))
print("Columns:", len(df.columns))

Cleaned dataset exported successfully!
File: D:\data_analyst_road_map\project\customer_churn\dataset\cleaned\customer_churn_cleaned.csv
Rows: 440832
Columns: 12

In [37]:
# ============================================================
# 25. CONNECT TO POSTGRESQL
# ============================================================

from sqlalchemy import create_engine

username = "postgres"
password = "12345"
host = "localhost"
port = "5432"
database = "customer_churn"

connection_string = (
    f"postgresql+psycopg2://"
    f"{username}:{password}@"
    f"{host}:{port}/{database}"
)

engine = create_engine(connection_string)

print("PostgreSQL connection created successfully!")

PostgreSQL connection created successfully!

In [38]:
# ============================================================
# 26. TEST POSTGRESQL CONNECTION
# ============================================================

from sqlalchemy import text

with engine.connect() as connection:
    result = connection.execute(
        text("SELECT version();")
    )

    version = result.fetchone()[0]

print("PostgreSQL connection successful!")
print("\nPostgreSQL version:")
print(version)

PostgreSQL connection successful!

PostgreSQL version:
PostgreSQL 18.4 on x86_64-windows, compiled by msvc-19.44.35226, 64-bit

In [43]:
# ============================================================
# 27. LOAD DATA INTO POSTGRESQL
# ============================================================

from sqlalchemy.types import String, Integer, Numeric

table_name = "customer_churn"

df.to_sql(
    table_name,
    engine,
    if_exists="replace",
    index=False,
    dtype={
        "customerid": String(50),
        "age": Integer(),
        "gender": String(20),
        "tenure": Integer(),
        "usage_frequency": Integer(),
        "support_calls": Integer(),
        "payment_delay": Integer(),
        "subscription_type": String(20),
        "contract_length": String(20),
        "total_spend": Numeric(12, 2),
        "last_interaction": Integer(),
        "churn": Integer()
    }
)

print("Data loaded successfully!")
print("Table:", table_name)
print("Rows:", len(df))

Data loaded successfully!
Table: customer_churn
Rows: 440832

In [40]:
# ============================================================
# 28. VERIFY POSTGRESQL TABLE
# ============================================================

query = """
SELECT *
FROM customer_churn
LIMIT 10;
"""

df_postgres = pd.read_sql(
    query,
    engine
)

df_postgres

,customerid,age,gender,tenure,usage_frequency,support_calls,payment_delay,subscription_type,contract_length,total_spend,last_interaction,churn
0,2.0,30,Female,39,14,5,18,Standard,Annual,932.0,17,1
1,3.0,65,Female,49,1,10,8,Basic,Monthly,557.0,6,1
2,4.0,55,Female,14,4,6,18,Basic,Quarterly,185.0,3,1
3,5.0,58,Male,38,21,7,7,Standard,Monthly,396.0,29,1
4,6.0,23,Male,32,20,5,8,Basic,Monthly,617.0,20,1
5,8.0,51,Male,33,25,9,26,Premium,Annual,129.0,8,1
6,9.0,58,Female,49,12,3,16,Standard,Quarterly,821.0,24,1
7,10.0,55,Female,37,8,4,15,Premium,Annual,445.0,30,1
8,11.0,39,Male,12,5,7,4,Standard,Quarterly,969.0,13,1
9,12.0,64,Female,3,25,2,11,Standard,Quarterly,415.0,29,1

In [41]:
# ============================================================
# 29. CHECK ROW COUNT
# ============================================================

query = """
SELECT COUNT(*) AS total_customers
FROM customer_churn;
"""

result = pd.read_sql(
    query,
    engine
)

result

   total_customers
0           440832

In [44]:
# ============================================================
# 30. CHECK POSTGRESQL DATA TYPES
# ============================================================

query = """
SELECT
    column_name,
    data_type
FROM information_schema.columns
WHERE table_name = 'customer_churn'
ORDER BY ordinal_position;
"""

postgres_schema = pd.read_sql(
    query,
    engine
)

postgres_schema

          column_name          data_type
0          customerid  character varying
1                 age            integer
2              gender  character varying
3              tenure            integer
4     usage_frequency            integer
5       support_calls            integer
6       payment_delay            integer
7   subscription_type  character varying
8     contract_length  character varying
9         total_spend            numeric
10   last_interaction            integer
11              churn            integer

In [45]:
# ============================================================
# 31. FINAL POSTGRESQL VALIDATION
# ============================================================

query = """
SELECT
    COUNT(*) AS total_rows,
    COUNT(customerid) AS customerid_count,
    COUNT(*) - COUNT(customerid) AS missing_customerid,
    COUNT(*) - COUNT(churn) AS missing_churn
FROM customer_churn;
"""

final_check = pd.read_sql(
    query,
    engine
)

final_check

   total_rows  customerid_count  missing_customerid  missing_churn
0      440832            440832                   0              0